/**
 * Map of technology identifiers to their display names
 * Used for normalizing tech stack names and displaying proper labels
 */
/**
 * Map of technology identifiers to their display names
 * Used for normalizing tech stack names and displaying proper labels
 */
export const iconStackMapping = {
  //Frontend
  react: 'React',
  nextjs: 'Next.js',
  vuejs: 'Vue.js',
  angular: 'Angular',
  svelte: 'Svelte',
  astro: 'Astro',
  //Backend
  express: 'Express',
  nodejs: 'Node.js',
  django: 'Django',
  flask: 'Flask',
  laravel: 'Laravel',
  rails: 'Ruby on Rails',
  //Mobile
  reactnative: 'React Native',
  flutter: 'Flutter',
  androidstudio: 'Android Studio',
  xcode: 'Xcode',
  //Languages
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  java: 'Java',
  ruby: 'Ruby',
  php: 'PHP',
  c: 'C',
  go: 'Go',
  rust: 'Rust',
  kotlin: 'Kotlin',
  swift: 'Swift',
  //Styling
  css: 'CSS',
  scss: 'SCSS',
  sass: 'SASS',
  tailwind: 'Tailwind CSS',
  bootstrap: 'Bootstrap',
  less: 'Less',
  //Database
  mongodb: 'MongoDB',
  mongoose: 'Mongoose',
  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  sqlite: 'SQLite',
  redis: 'Redis',
  firebase: 'Firebase',
  supabase: 'Supabase',
  //DevOps / Cloud
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  aws: 'AWS',
  azure: 'Azure',
  gcp: 'GCP',
  vercel: 'Vercel',
  netlify: 'Netlify',
  nginx: 'Nginx',
  jenkins: 'Jenkins',
  circleci: 'CircleCI',
  travisci: 'Travis CI',
  githubactions: 'GitHub Actions',
  argo: 'ArgoCD',
  helm: 'Helm',
  terraform: 'Terraform',
  pulumi: 'Pulumi',
  ansible: 'Ansible',
  prometheus: 'Prometheus',
  grafana: 'Grafana',
  datadog: 'Datadog',
  newrelic: 'New Relic',
  sentry: 'Sentry',
  sonar: 'SonarQube',
  vault: 'Vault',
  trivy: 'Trivy',
  cloudflare: 'Cloudflare',
  digitalocean: 'DigitalOcean',
  heroku: 'Heroku',
  //Cybersecurity
  burpsuite: 'Burp Suite',
  metasploit: 'Metasploit',
  nmap: 'Nmap',
  wireshark: 'Wireshark',
  zap: 'OWASP ZAP',
  //QA / Testing
  jest: 'Jest',
  mocha: 'Mocha',
  cypress: 'Cypress',
  playwright: 'Playwright',
  vitest: 'Vitest',
  testinglibrary: 'Testing Library',
  selenium: 'Selenium',
  testcafe: 'TestCafe',
  puppeteer: 'Puppeteer',
  chai: 'Chai',
  jasmine: 'Jasmine',
  karma: 'Karma',
  postman: 'Postman',
  newman: 'Newman',
  jmeter: 'JMeter',
  locust: 'Locust',
  allure: 'Allure',
  cucumber: 'Cucumber',
  pact: 'Pact',
  mockserver: 'MockServer',
  //CMS / Auth
  sanity: 'Sanity',
  strapi: 'Strapi',
  contentful: 'Contentful',
  auth0: 'Auth0',
  //Data Science / ML / AI
  pandas: 'Pandas',
  numpy: 'NumPy',
  scipy: 'SciPy',
  matplotlib: 'Matplotlib',
  seaborn: 'Seaborn',
  plotly: 'Plotly',
  scikitlearn: 'Scikit-learn',
  tensorflow: 'TensorFlow',
  pytorch: 'PyTorch',
  keras: 'Keras',
  xgboost: 'XGBoost',
  lightgbm: 'LightGBM',
  fastai: 'FastAI',
  jupyter: 'Jupyter',
  colab: 'Google Colab',
  kaggle: 'Kaggle',
  mlflow: 'MLflow',
  databricks: 'Databricks',
  huggingface: 'Hugging Face',
  openai: 'OpenAI',
  langchain: 'LangChain',
  //UX / UI Design
  figma: 'Figma',
  adobexd: 'Adobe XD',
  sketch: 'Sketch',
  invision: 'InVision',
  //CI/CD & Tools
  github: 'GitHub',
  git: 'Git',
  gitlab: 'GitLab',
  bitbucket: 'Bitbucket',
  eslint: 'ESLint',
  prettier: 'Prettier',
  vite: 'Vite',
  webpack: 'Webpack',
  babel: 'Babel',
  pnpm: 'PNPM',
  yarn: 'Yarn',
  npm: 'NPM',
  //Project / Documentation / Architecture
  notion: 'Notion',
  jira: 'Jira',
  trello: 'Trello',
  miro: 'Miro',
  drawio: 'Draw.io',
  plantuml: 'PlantUML',
  swagger: 'Swagger',
  openapi: 'OpenAPI',
  //Other
  prisma: 'Prisma',
  graphql: 'GraphQL',
  apollo: 'Apollo',
  storybook: 'Storybook',
  threejs: 'Three.js',
};
