/**
 * Map of technology identifiers to their display names
 * Used for normalizing tech stack names and displaying proper labels
 */
export const iconStackMapping = {
  //Frontend
  react: 'React',
  nextjs: 'Next.js',
  vuejs: 'Vue.js',
  angular: 'Angular',
  svelte: 'Svelte',
  astro: 'Astro',
  //Backend
  express: 'Express',
  nodejs: 'Node.js',
  django: 'Django',
  flask: 'Flask',
  laravel: 'Laravel',
  rails: 'Ruby on Rails',
  //Languages
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  js: 'JavaScript',
  python: 'Python',
  java: 'Java',
  ruby: 'Ruby',
  php: 'PHP',
  c: 'C',
  go: 'Go',
  rust: 'Rust',
  kotlin: 'Kotlin',
  swift: 'Swift',
  // Styling
  css: 'CSS',
  scss: 'SCSS',
  sass: 'SASS',
  tailwind: 'Tailwind CSS',
  bootstrap: 'Bootstrap',
  less: 'Less',
  //DB
  mongodb: 'MongoDB',
  mongoose: 'Mongoose',
  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  sqlite: 'SQLite',
  redis: 'Redis',
  firebase: 'Firebase',
  supabase: 'Supabase',
  //DevOps / Cloud
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  aws: 'AWS',
  azure: 'Azure',
  gcp: 'GCP',
  vercel: 'Vercel',
  netlify: 'Netlify',
  nginx: 'Nginx',
  //CI/CD & Tools
  github: 'GitHub',
  git: 'Git',
  gitlab: 'GitLab',
  bitbucket: 'Bitbucket',
  eslint: 'ESLint',
  prettier: 'Prettier',
  vite: 'Vite',
  webpack: 'Webpack',
  babel: 'Babel',
  pnpm: 'PNPM',
  yarn: 'Yarn',
  npm: 'NPM',
  //Testing
  jest: 'Jest',
  mocha: 'Mocha',
  cypress: 'Cypress',
  playwright: 'Playwright',
  vitest: 'Vitest',
  testinglibrary: 'Testing Library',
  //CMS / Auth
  sanity: 'Sanity',
  strapi: 'Strapi',
  contentful: 'Contentful',
  auth0: 'Auth0',
  //Others
  prisma: 'Prisma',
  graphql: 'GraphQL',
  apollo: 'Apollo',
  storybook: 'Storybook',
  threejs: 'Three.js',
  figma: 'Figma',
};
