/**
 * Map of technology identifiers to their display names
 * Used for normalizing tech stack names and displaying proper labels
 */
/**
 * Map of technology identifiers to their display names
 * Used for normalizing tech stack names and displaying proper labels
 */
export const iconStackMapping = {
  //Frontend
  angular: 'Angular',
  astro: 'Astro',
  backbone: 'Backbone.js',
  ember: 'Ember.js',
  lit: 'Lit',
  nextjs: 'Next.js',
  nuxt: 'Nuxt.js',
  preact: 'Preact',
  qwik: 'Qwik',
  react: 'React',
  remix: 'Remix',
  solidjs: 'Solid.js',
  svelte: 'Svelte',
  vuejs: 'Vue.js',
  // Backend
  adonisjs: 'AdonisJS',
  aspnet: 'ASP.NET Core',
  cakephp: 'CakePHP',
  codeigniter: 'CodeIgniter',
  django: 'Django',
  express: 'Express',
  fastapi: 'FastAPI',
  flask: 'Flask',
  hapi: 'Hapi.js',
  koa: 'Koa.js',
  laravel: 'Laravel',
  nestjs: 'Nest.js',
  nodejs: 'Node.js',
  phoenix: 'Phoenix (Elixir)',
  rails: 'Ruby on Rails',
  springboot: 'Spring Boot',
  symfony: 'Symfony',
  yii: 'Yii',
  zend: 'Zend Framework',
  //Mobile
  androidstudio: 'Android Studio',
  expo: 'Expo',
  flutter: 'Flutter',
  reactnative: 'React Native',
  xcode: 'Xcode',
  //Languages
  c: 'C',
  cpp: 'C++',
  go: 'Go',
  java: 'Java',
  javascript: 'JavaScript',
  kotlin: 'Kotlin',
  php: 'PHP',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  swift: 'Swift',
  typescript: 'TypeScript',
  //Styling
  bootstrap: 'Bootstrap',
  css: 'CSS',
  less: 'Less',
  postcss: 'PostCSS',
  sass: 'SASS',
  scss: 'SCSS',
  tailwind: 'Tailwind CSS',
  //Database
  firebase: 'Firebase',
  mongoose: 'Mongoose',
  mongodb: 'MongoDB',
  mysql: 'MySQL',
  postgresql: 'PostgreSQL',
  redis: 'Redis',
  sqlite: 'SQLite',
  supabase: 'Supabase',
  // ORM
  sequelize: 'Sequelize',
  prisma: 'Prisma',
  typeorm: 'TypeORM',
  mikroorm: 'MikroORM',
  objection: 'Objection.js',
  waterline: 'Waterline',
  hibernate: 'Hibernate',
  doctrine: 'Doctrine ORM',
  //DevOps / Cloud
  ansible: 'Ansible',
  argo: 'ArgoCD',
  aws: 'AWS',
  azure: 'Azure',
  cloudflare: 'Cloudflare',
  circleci: 'CircleCI',
  datadog: 'Datadog',
  digitalocean: 'DigitalOcean',
  docker: 'Docker',
  gcp: 'GCP',
  githubactions: 'GitHub Actions',
  helm: 'Helm',
  heroku: 'Heroku',
  jenkins: 'Jenkins',
  kubernetes: 'Kubernetes',
  netlify: 'Netlify',
  newrelic: 'New Relic',
  nginx: 'Nginx',
  prometheus: 'Prometheus',
  pulumi: 'Pulumi',
  sentry: 'Sentry',
  sonar: 'SonarQube',
  terraform: 'Terraform',
  trivy: 'Trivy',
  vault: 'Vault',
  vercel: 'Vercel',
  //Cybersecurity
  burpsuite: 'Burp Suite',
  metasploit: 'Metasploit',
  nmap: 'Nmap',
  wireshark: 'Wireshark',
  zap: 'OWASP ZAP',
  //QA / Testing
  allure: 'Allure',
  chai: 'Chai',
  cucumber: 'Cucumber',
  cypress: 'Cypress',
  jasmine: 'Jasmine',
  jest: 'Jest',
  jmeter: 'JMeter',
  karma: 'Karma',
  locust: 'Locust',
  mockserver: 'MockServer',
  mocha: 'Mocha',
  newman: 'Newman',
  pact: 'Pact',
  playwright: 'Playwright',
  postman: 'Postman',
  puppeteer: 'Puppeteer',
  selenium: 'Selenium',
  testcafe: 'TestCafe',
  testinglibrary: 'Testing Library',
  vitest: 'Vitest',
  //CMS / Auth
  auth0: 'Auth0',
  clerk: 'Clerk',
  contentful: 'Contentful',
  sanity: 'Sanity',
  strapi: 'Strapi',
  //Data Science / ML / AI
  colab: 'Google Colab',
  databricks: 'Databricks',
  fastai: 'FastAI',
  huggingface: 'Hugging Face',
  jupyter: 'Jupyter',
  kaggle: 'Kaggle',
  keras: 'Keras',
  langchain: 'LangChain',
  lightgbm: 'LightGBM',
  matplotlib: 'Matplotlib',
  mlflow: 'MLflow',
  numpy: 'NumPy',
  openai: 'OpenAI',
  pandas: 'Pandas',
  plotly: 'Plotly',
  scikitlearn: 'Scikit-learn',
  scipy: 'SciPy',
  seaborn: 'Seaborn',
  tensorflow: 'TensorFlow',
  xgboost: 'XGBoost',
  //UX / UI Design
  adobexd: 'Adobe XD',
  figma: 'Figma',
  invision: 'InVision',
  sketch: 'Sketch',
  //CI/CD & Tools
  babel: 'Babel',
  eslint: 'ESLint',
  github: 'GitHub',
  git: 'Git',
  gitlab: 'GitLab',
  npm: 'NPM',
  pnpm: 'PNPM',
  prettier: 'Prettier',
  vite: 'Vite',
  webpack: 'Webpack',
  yarn: 'Yarn',
  //Project / Documentation / Architecture
  drawio: 'Draw.io',
  miro: 'Miro',
  notion: 'Notion',
  openapi: 'OpenAPI',
  plantuml: 'PlantUML',
  swagger: 'Swagger',
  trello: 'Trello',
  jira: 'Jira',
  //Other
  apollo: 'Apollo',
  bun: 'Bun',
  electron: 'Electron',
  graphql: 'GraphQL',
  storybook: 'Storybook',
  threejs: 'Three.js',
};
