name: Deploy Production - DivBrainers

on:
  push:
    branches: [main]

jobs:
  vercel-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          ORIGIN_REGEX: ^https:\/\/divbrainers\.com$

      - name: Deploy to Vercel (Prod)
        if: github.event_name == 'push'
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
