name: Deploy Production - DivBrainers

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  vercel-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          ORIGIN_REGEX: ^https:\/\/divbrainers\.com$

      - name: Deploy to Vercel (Prod)
        if: github.event_name == 'push'
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
