name: Deploy Production - DivBrainers

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  vercel-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 22.14.0 }
      - run: npm ci
      - run: npm run build
        env:
          ORIGIN_REGEX: ^https:\/\/divbrainers\.com$

      - name: Deploy to Vercel (Prod)
        if: github.event_name == 'push'
        run: npx vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
