name: Deploy Preview - DivBrainers

on:
  push:
    branches: [preview]

jobs:
  vercel-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          ORIGIN_REGEX: ^https:\/\/divbrainers\.vercel\.app$

      - name: Deploy to Vercel (Preview)
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --target=preview --confirm
